Audience/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('main/', views.main_view, name='main_view'),
    path('search/<str:keyword>/<str:category>/<str:board_type>/<str:post_type>/<str:search_type>/', views.search_page,
         name='search_page'),
    path('search/<str:category>/<str:board_type>/<str:post_type>/<str:search_type>/', views.post_list_page,
         name='post_list_page'),
    path('search/posts/keyword/', views.search_posts, name='search_posts'),
    path('search/posts/', views.post_list, name='post_list'),
    path("total_pages/",views.total_page,name = "total_page")
    # category: 구인/구직, board_type: Free or not, post_type: 구인 -> 관심 분야/신입/경력, search_type: 검색 조건
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Audience import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employ/', include('employ.urls')),
    path('job/', include('job.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include('account.urls')),
    path('util/', include('util.urls')),
    path('audience/', include('Audience.urls')),
    path('', views.intro_view, name='intro_view'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employ/urls.py
from django.urls import path
from . import views as views

app_name = "employ"
urlpatterns = [
    path('<int:post_id>/', views.employ_post_detail, name='employ_post_detail'),
    path('create/', views.create_employ_post, name='create_employ_post'),
    path('update/<int:id>/', views.update_employ_post, name='update_employ_post'),
    path('delete/<int:id>/', views.delete_employ_post, name='delete_employ_post'),
    path('freepost/<int:post_id>/', views.employ_free_post_detail, name='employ_free_post_detail'),
    path('freepost/create/', views.create_employ_free_post, name='create_employ_free_post'),
    path('freepost/update/<int:id>/', views.update_employ_free_post, name='update_employ_free_post'),
    path('freepost/delete/<int:id>/', views.delete_employ_free_post, name='delete_employ_free_post'),
    path("question/list/", views.QA_list_data, name="QA_list_data"),
    path("question/list/<int:id>", views.QA_list, name="QA_list"),
    path('question/create/<int:post_id>/', views.create_question, name='create_question'),
    path('question/update/<int:post_id>/', views.update_question, name='update_question'),
    path('question/<int:post_id>/<int:question_id>/', views.question_detail, name='question_detail'),
    path('question/delete/<int:post_id>/', views.delete_question, name='delete_question'),
    path('answer/create/<int:post_id>/<int:question_id>/', views.create_answer, name='create_answer'),
    path('answer/update/<int:post_id>/<int:question_id>/', views.update_answer, name='update_answer'),
    path('answer/delete/<int:post_id>/<int:question_id>/', views.delete_answer, name='delete_answer'),
    path("report/create/", views.report_create_e, name="report_create_e"),
    path('post/<int:post_id>/', views.post_detail, name='post_detail')
]

job/urls.py
from django.urls import path
from . import views as views

app_name = "job"
urlpatterns = [
    path('<int:post_id>/', views.job_post_detail, name='job_post_detail'),
    path('create/', views.create_job_post, name='create_job_post'),
    path('update/<int:id>/',views.update_job_post,name='update_job_post'),
    path('delete/<int:id>/',views.delete_job_post,name='delete_job_post'),
    path('freepost/<int:post_id>/', views.job_free_post_detail, name='job_free_post_detail'),
    path('freepost/create/', views.create_job_free_post, name='create_job_free_post'),
    path('freepost/update/<int:id>/', views.update_job_free_post, name='update_job_free_post'),
    path('freepost/delete/<int:id>/', views.delete_job_free_post, name='delete_job_free_post'),
    path("report/create/", views.report_create_j, name="report_create_j"),
    path("company/search/", views.search_company, name="search_company"),
]

templates/change_c.html
{% extends 'header.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/mypage_css/change_c_p.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="/static/js/signup_change.js"></script>

    <title>기업 회원정보수정</title>
</head>
{% endblock %}
{% block content %}
<body>
    <h1 class="serviceName">청취자들</h1>

    <div class="change_p">
        <form action="{% url 'update_account' %}" method="POST" enctype="multipart/form-data">
            <div class="id">
                <h3 class="h3_id">아이디</h3>
                <input type="text" class="user_id" value="{{user.username}}" disabled>
            </div>
            <div class="pw">
                <h3 class="h3_pw">비밀번호</h3>
                <input type="button" class="change_pw" value="비밀번호 변경하기" onclick="location.href='{% url 'update_password' %}'">
            </div>
            <input type="password" class="user_pw" value="**********" disabled></input>
            <div class="name">
                <h3 class="h3_name">회사이름</h3>
                <input class="user_name" name= "company" value="{{detail_user.company}}"></input>
            </div>
            
            <div class="interesting">
                <h3 class="h3_interest">관심분야</h3>
                <div class="interest_table">
                    <input type="checkbox" id="checkbox1" class="interest_button" name="interest" value="전기전자">
                    <input type="checkbox" id="checkbox2" class="interest_button" name="interest" value="조선업">
                    <input type="checkbox" id="checkbox3" class="interest_button" name="interest" value="it">
                    <input type="checkbox" id="checkbox4" class="interest_button" name="interest" value="의료">
                    <input type="checkbox" id="checkbox5" class="interest_button" name="interest" value="디지털">
                    <input type="checkbox" id="checkbox6" class="interest_button" name="interest" value="기획전략">
                    <input type="checkbox" id="checkbox7" class="interest_button" name="interest" value="의류산업">
                    <input type="checkbox" id="checkbox8" class="interest_button" name="interest" value="교육">
                    <input type="checkbox" id="checkbox9" class="interest_button" name="interest" value="금융">
                    <input type="checkbox" id="checkbox10" class="interest_button" name="interest" value="상품기획">
                    <input type="checkbox" id="checkbox11" class="interest_button" name="interest" value="물류">
                    <input type="checkbox" id="checkbox12" class="interest_button" name="interest" value="회계재무">
                    <input type="checkbox" id="checkbox13" class="interest_button" name="interest" value="서비스">
                    <input type="checkbox" id="checkbox14" class="interest_button" name="interest" value="공공복지">
                    <input type="checkbox" id="checkbox15" class="interest_button" name="interest" value="미디어">
                    <input type="checkbox" id="checkbox16" class="interest_button" name="interest" value="농림어업">
                    <input type="checkbox" id="checkbox17" class="interest_button" name="interest" value="건설토목">
                    <input type="checkbox" id="checkbox18" class="interest_button" name="interest" value="스포츠레크레이션">
                    <label for="checkbox1" id="old_label_1" class="change_label" onclick="button_2()"><span class="change_span">전기전자</span></label>
                    <label for="checkbox2" id="old_label_2" class="change_label" onclick="button_2()"><span class="change_span">조선업</span></label>
                    <label for="checkbox3" id="old_label_3" class="change_label" onclick="button_2()"><span class="change_span">IT</span></label>
                    <label for="checkbox4" id="old_label_4" class="change_label" onclick="button_2()"><span class="change_span">의료</span></label>
                    <label for="checkbox5" id="old_label_5" class="change_label" onclick="button_2()"><span class="change_span">디지털</span></label>
                    <label for="checkbox6" id="old_label_6" class="change_label" onclick="button_2()"><span class="change_span">기획전략</span></label>
                    <label for="checkbox7" id="old_label_7" class="change_label" onclick="button_2()"><span class="change_span">의류산업</span></label>
                    <label for="checkbox8" id="old_label_8" class="change_label" onclick="button_2()"><span class="change_span">교육</span></label>
                    <label for="checkbox9" id="old_label_9" class="change_label" onclick="button_2()"><span class="change_span">금융</span></label>
                    <label for="checkbox10" id="old_label_10" class="change_label" onclick="button_2()"><span class="change_span">상품기획/MD</span></label>
                    <label for="checkbox11" id="old_label_11" class="change_label" onclick="button_2()"><span class="change_span">물류</span></label>
                    <label for="checkbox12" id="old_label_12" class="change_label" onclick="button_2()"><span class="change_span">회계/재무</span></label>
                    <label for="checkbox13" id="old_label_13" class="change_label" onclick="button_2()"><span class="change_span">서비스</span></label>
                    <label for="checkbox14" id="old_label_14" class="change_label" onclick="button_2()"><span class="change_span">공공복지</span></label>
                    <label for="checkbox15" id="old_label_15" class="change_label" onclick="button_2()"><span class="change_span">미디어</span></label>
                    <label for="checkbox16" id="old_label_16" class="change_label" onclick="button_2()"><span class="change_span">농림/어업</span></label>
                    <label for="checkbox17" id="old_label_17" class="change_label" onclick="button_2()"><span class="change_span">건설/토목</span></label>
                    <label for="checkbox18" id="old_label_18" class="change_label" onclick="button_2()"><span class="change_span">스포츠/레크레이션</span></label>
                </div>
            </div>
            

            <div class="career">
                <h3 class="h3_career">회사 로고 첨부</h3>

                <input type="file" id="input_file" class="input_file" name="image" onchange="display_filename(this)">
                <p id="filename"></p>
                <label for="input_file" class="input_career">이미지첨부</label>
            </div>
            <div class="change_button_wrap">
                <input type="submit" class="change_button" value="회원정보 수정하기">
            </div>
        </form>
        <div class="delete">
            <a href="{% url 'delete_account' %}" class="move_delete_p">계정삭제하기</a>
        </div>
    </div>

</body>
{% endblock %}
</html>

templates/change_complete.html
{% extends 'header.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/mypage_css/change_complete.css">
    <title>회원정보수정완료 팝업</title>
</head>
{% endblock %}
{% block content %}
<body>
    <form action="" class="pop_up">
        <div class="pop_up">
            <div class="close">
                <img src="/static/img/Union.png" alt="x">
            </div>
                <h2 class="text">회원정보 수정이 완료되었습니다</h2>

            <input type="button" class="complete" value="확인" onclick="location.href='{% url 'my_page' %}'">
        </div>
    </form>
    <!-- onclick='location.href'=login.html' -->
</body>
{% endblock %}
</html>

templates/changepw_complete.html
{% extends 'header.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/mypage_css/change_complete.css">
    <title>비밀번호수정완료 팝업</title>
</head>
{% endblock %}
{% block content %}
<body>
    <form action="" class="pop_up">
        <div class="pop_up">
            <div class="close">
                <img src="/static/img/Union.png" alt="x">
            </div>
                <h2 class="text">비밀번호 변경이 완료되었습니다<br>다시 로그인하세요</h2>

            <input type="button" class="complete" value="확인" onclick="location.href='/account/login/'">
        </div>
    </form>
    <!-- onclick='location.href'=login.html' -->
</body>
{% endblock %}
</html>

templates/create_post_view.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    .form-container {
      max-width: 500px;
      margin: 0 auto;
      padding: 20px;
      background-color: #ffffff; /* Changed to white */
      border: 2px solid #ffffff; /* Changed to white */
      border-radius: 8px; /* Changed to less rounded corners */
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .form-container label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    .form-container select,
    .form-container input[type="text"],
    .form-container textarea {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      margin-bottom: 10px;
      background-color: #ffffff; /* Changed to white */
    }

    .form-container textarea {
      height: 200px;
    }

    .form-container button {
      background-color: #e286aa;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    .form-container button:hover {
      background-color: #d16a8f;
    }
  </style>
</head>
<body>
  <div class="form-container">
    <form action="{% url 'create_post_view' %}" method="post">
      {% csrf_token %}
{% if user.type == '구직자' %}
{% else %} {% endif %}
      <label for="category">카테고리:</label>
      <select id="category" name="category">
        <option disabled selected>선택</option>
        <optgroup label="구직">
          {% if user.type == '구직자' %}
            <option value="1">구직</option>
          {% else %}
            <option disabled selected>구직</option>
          {% endif %}
          <option value="2">자유</option>
        </optgroup>
        <optgroup label="구인">
          {% if user.type == '구직자' %}
            <option disabled selected>경력</option>
            <option disabled selected>신입</option>
          {% else %}
            <option value="3">경력</option>
            <option value="4">신입</option>
          {% endif %}
          <option value="5">자유</option>
        </optgroup>
      </select>

      <label for="title">제목:</label>
      <input type="text" id="title" name="title">

      <label for="title">회사:</label>
      <input type="text" id="titl" name="title">

      <label for="content">내용:</label>
      <textarea id="content" name="content"></textarea>

      <button type="submit">작성</button>
    </form>
  </div>
</body>
</html>

templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="kr">
<head>
	<meta name="code" charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes"/>
	<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
	<script src="/static/js/header.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/header_style.css"/>
    {% block static %}
    {% endblock %}
</head>
<body>
	<div class="vh-container">
		<!-- header -->
		<header class="vh-header">
			<!-- main header -->
			<div class="hd-main-wrap">
				<a class="logo" href="{% url 'main:main_view' %}" alt="홈으로">
					<img src="/static/img/logo/logo-symbol.png" class="logo-symbol">
					<img src="/static/img/logo/logo-text.png" class="logo-text">
				</a>
				<div class="search-wrap">
					<div class="search-box">
					  <input type="text" id="keyword-input" placeholder="검색"  >
					  <button type="button" id="search-button" title="검색" ></button>
					</div>
				  </div>
				{% if not user.is_authenticated %}
					<div class="tool">
						<a href="{% url 'account_login' %}">로그인</a>
						<a href="{% url 'signup_page' %}">회원가입</a>
					</div>
				{% else %}
					<div class="tool">
						<a href="{% url 'account_logout' %}">로그아웃</a>
						<a href="{% url 'my_page' %}">마이페이지</a>
						<a href="{% url 'create_post_view' %}">글쓰기</a>
					</div>
				{% endif %}
			</div>
			<!-- scrolling header -->
			<div class="hd-gnb-wrap scroll-head">
				<!-- gnb -->
				<div class="hd-gnb">
					<div class="hd-gnb-trigger"></div>
					<div class="hd-gnb-menu">
						<ul>
							<li>
								<a href="{% url 'main:post_list_page' '구인' 'all' 'all' 'all' %}" class="depth-title">채용정보</a>
								<ul class="hd-gnb-depth">
									<li><a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}">구인글</a></li>
									<li><a href="{% url 'main:post_list_page' '구인' 'free' 'all' 'all' %}">자유소통</a></li>
								</ul>
							</li>
							<li>
								<a href="{% url 'main:post_list_page' '구직' 'all' 'all' 'all' %}" class="depth-title">청취자</a>
								<ul class="hd-gnb-depth">
									<li><a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}">구직자들(평점,후기)</a></li>
									<li><a href="{% url 'main:post_list_page' '구직' 'free' 'all' 'all' %}">자유소통</a></li>
								</ul>
							</li>
							<li><a href="{% url 'intro_view' %}" class="depth-title">소개</a></li>
						</ul>
					</div>
				</div>
				<!-- gnb // -->
				<!-- drop menu -->
				<div class="he-gnb-drop">
					<ul>
						<li>
							<a href="{% url 'main:post_list_page' '구인' 'all' 'all' 'all' %}" class="depth-title">채용정보</a>
							<ul class="hd-gnb-depth">
								<li><a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}">구인글</a></li>
								<li><a href="{% url 'main:post_list_page' '구직' 'free' 'all' 'all' %}">자유소통</a></li>
							</ul>
						</li>
						<li>
							<a href="{% url 'main:post_list_page' '구직' 'all' 'all' 'all' %}" class="depth-title">청취자</a>
							<ul class="hd-gnb-depth">
								<li><a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}">구직자들(평점,후기)</a></li>
								<li><a href="{% url 'main:post_list_page' '구직' 'free' 'all' 'all' %}">자유소통</a></li>
							</ul>
						</li>
						<li>
							<a href="{% url 'intro_view' %}" class="depth-title">소개</a>
						</li>
					</ul>
				</div>
				<!-- drop menu // -->
			</div>
		</header>
	{% block content %}
    {% endblock %}

	<script type="text/javascript">
		// header gnb trigger 
		$('.hd-gnb-trigger').on('click', function(e){
			$('.hd-gnb-wrap').toggleClass('open');
		});
		var post = {};
	</script>
</body>
</html>

templates/header2.html
{% load static %}

<!DOCTYPE html>
<html lang="kr">
{% block static %}
<head>
	<meta name="code" charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes"/>
	<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
	<script src="/static/js/header2.js"></script>

	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/header2_style.css"/>
</head>
{% endblock %}
{% block content %}
<body>
	<div class="vh-container">
		<!-- header -->
		<header class="vh-header">
			<!-- main header -->
			<div class="hd-main-wrap">
				<a class="logo" href="{% url 'main:main_view' %}" alt="홈으로">
					<img src="/static/img/logo/logo-symbol.png" class="logo-symbol">
					<img src="/static/img/logo/logo-text.png" class="logo-text">
				</a>	

				<!-- scrolling header -->
			<div class="hd-gnb-wrap scroll-head">
				<!-- gnb -->
				<div class="hd-gnb">
					<div class="hd-gnb-trigger"></div>
					<div class="hd-gnb-menu">
						<ul>
							<li>
								<a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}" class="depth-title">채용정보</a>
								<ul class="hd-gnb-depth">
									<li><a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}">구인글</a></li>
									<li><a href="{% url 'main:post_list_page' '구인' 'free' 'all' 'all' %}">자유소통</a></li>
								</ul>
							</li>
							<li>
								<a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}" class="depth-title">청취자</a>
								<ul class="hd-gnb-depth">
									<li><a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}">구직자들(평점,후기)</a></li>
									<li><a href="{% url 'main:post_list_page' '구직' 'free' 'all' 'all' %}">자유소통</a></li>
								</ul>
							</li>
							<li><a href="{% url 'intro_view' %}" class="depth-title">소개</a></li>
						</ul>
					</div>
				</div>
				<!-- gnb // -->
				<!-- drop menu -->
				<div class="he-gnb-drop">
					<ul>
						<li>
							<a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}" class="depth-title">채용정보</a>
							<ul class="hd-gnb-depth">
								<li><a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}">구인글</a></li>
								<li><a href="{% url 'main:post_list_page' '구인' 'free' 'all' 'all' %}">자유소통</a></li>
							</ul>
						</li>
						<li>
							<a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}" class="depth-title">청취자</a>
							<ul class="hd-gnb-depth">
								<li><a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}">구직자들(평점,후기)</a></li>
								<li><a href="{% url 'main:post_list_page' '구직' 'free' 'all' 'all' %}">자유소통</a></li>
							</ul>
						</li>
						<li>
							<a href="{% url 'intro_view' %}" class="depth-title">소개</a>
						</li>
					</ul>
				</div>
				<!-- drop menu // -->
			</div>
			{% if not user.is_authenticated %}
				<div class="tool">
					<a href="{% url 'account_login' %}">로그인</a>
					<a href="{% url 'signup_page' %}">회원가입</a>
				</div>
			{% else %}
				<div class="tool">
					<a href="{% url 'account_logout' %}">로그아웃</a>
					<a href="{% url 'my_page' %}">마이페이지</a>
				</div>
			{% endif %}
			</div>			
		</header>
		

	<script type="text/javascript">
		// header gnb trigger 
		$('.hd-gnb-trigger').on('click', function(e){
			$('.hd-gnb-wrap').toggleClass('open');
		});
	</script>
</body>
{% endblock %}
</html>

templates/intro.html
{% extends 'header.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="kr">

<head>
	{% block static %}
	<meta name="code" charset="utf-8">
	<meta name="viewport"
		content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes" />
	<script src="https://code.jquery.com/jquery-3.7.0.min.js"
		integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
	<script src="/static/js/header.js"></script>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap"
		rel="stylesheet">
	<link rel="stylesheet" href="../static/css/intro_style.css" />
	{% endblock %}

</head>
{% block content %}
<body>
	<!-- content  -->
	<div class="vh-content">
		<!-- main visual -->
		<div class="main-visual-wrap">
			<div class="main-visual-inner">
				<div class="visual-img"><img src="/static/img/demo/p logo.png"></div>
				<div class="text-img">
					<div class="title-img"><img src="/static/img/demo/p txt1.png"></div>
					<div class="sub-img"><img src="/static/img/demo/p txt2.png"></div>
					<div class="content-img"><img src="/static/img/demo/p txt3.png"></div>
					<a href="{% url 'main:main_view' %}" class="golink">홈으로 돌아가기</a>
				</div>
			</div>
		</div>
	</div>
	<!-- main visual // -->

	</div>

	<script type="text/javascript">
		// header gnb trigger 
		$('.hd-gnb-trigger').on('click', function (e) {
			$('.hd-gnb-wrap').toggleClass('open');
		});
	</script>

</body>
{% endblock %}
</html>

templates/main.html
{% extends 'header.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="kr">
{% block static %}
<head>
	<meta name="code" charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes"/>
	<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
	<script src="../../static/js/header.js"></script>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="../../static/css/main_style.css"/>
</head>
{% endblock %}
{% block content %}
<body>
	

		<!-- content  -->
		<div class="vh-content">
			<!-- main visual -->
			<div class="main-visual-wrap">
				<div class="main-visual-inner">
					<div class="visual-text">
						<div class="sub-text">청년 취업을 하기위한 사람들</div>
						<h1 class="title-text">청취자들</h1>
						<a href="{% url 'intro_view' %}" class="golink">자세히 알아보기</a>
					</div>
					<div class="visual-img"><img src="../../static/img/demo/demo-visual.png"></div>
				</div>
			</div>
			<!-- main visual // -->
			<!-- main bbs -->
			<div class="group-twin-wrap">
				<div class="group-item">
					<div class="bbs-list-wrap">
						<div class="bbs-list-head">
							<div class="bbs-list-title">실시간 구인 게시글</div>
							<div class="bbs-list-tool">
								<a href="{% url 'main:post_list_page' '구인' '구인' 'all' 'all' %}">+더보기</a>
							</div>
						</div>
						<div class="bbs-list-body">
							<ul>
								{% for post in employ_posts %}
									<li><a href="{% url 'employ:employ_post_detail' post.id %}"><span class="bbs-subject">{{post.title}}</span> <span class="bbs-date">{{post.created_at|date:'y.m.d'}}</span></a></li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
				<div class="group-item">
					<div class="bbs-list-wrap">
						<div class="bbs-list-head">
							<div class="bbs-list-title">실시간 구직 게시글</div>
							<div class="bbs-list-tool">
								<a href="{% url 'main:post_list_page' '구직' '구직' 'all' 'all' %}">+더보기</a>
							</div>
						</div>
						<div class="bbs-list-body">
							<ul>
								{% for post in job_posts %}
									<li><a href="{% url 'job:job_post_detail' post.id %}"><span class="bbs-subject">{{post.title}}</span> <span class="bbs-date">{{post.created_at|date:'y.m.d'}}</span></a></li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- main bbs // -->
		</div>
	</div>

	<script type="text/javascript">
		// header gnb trigger 
		$('.hd-gnb-trigger').on('click', function(e){
			$('.hd-gnb-wrap').toggleClass('open');
		});
	</script>
</body>
{% endblock %}
</html>