config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Audience import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employ/', include('employ.urls')),
    path('job/', include('job.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include('account.urls')),
    path('util/', include('util.urls')),
    path('audience/', include('Audience.urls')),
    path('', views.intro_view, name='intro_view'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employ/urls.py
from django.urls import path
from . import views as views

app_name = "employ"
urlpatterns = [
    path('<int:post_id>/', views.employ_post_detail, name='employ_post_detail'),
    path('create/', views.create_employ_post, name='create_employ_post'),
    path('update/<int:id>/', views.update_employ_post, name='update_employ_post'),
    path('delete/<int:id>/', views.delete_employ_post, name='delete_employ_post'),
    path('freepost/<int:post_id>/', views.employ_free_post_detail, name='employ_free_post_detail'),
    path('freepost/create/', views.create_employ_free_post, name='create_employ_free_post'),
    path('freepost/update/<int:id>/', views.update_employ_free_post, name='update_employ_free_post'),
    path('freepost/delete/<int:id>/', views.delete_employ_free_post, name='delete_employ_free_post'),
    path("question/list/", views.QA_list_data, name="QA_list_data"),
    path("question/list/<int:id>", views.QA_list, name="QA_list"),
    path('question/create/<int:post_id>/', views.create_question, name='create_question'),
    path('question/update/<int:post_id>/', views.update_question, name='update_question'),
    path('question/<int:post_id>/<int:question_id>/', views.question_detail, name='question_detail'),
    path('question/delete/<int:post_id>/', views.delete_question, name='delete_question'),
    path('answer/create/<int:post_id>/<int:question_id>/', views.create_answer, name='create_answer'),
    path('answer/update/<int:post_id>/<int:question_id>/', views.update_answer, name='update_answer'),
    path('answer/delete/<int:post_id>/<int:question_id>/', views.delete_answer, name='delete_answer'),
    path("report/create/", views.report_create_e, name="report_create_e"),
    path('post/<int:post_id>/', views.post_detail, name='post_detail')
]

job/urls.py
from django.urls import path
from . import views as views

app_name = "job"
urlpatterns = [
    path('<int:post_id>/', views.job_post_detail, name='job_post_detail'),
    path('create/', views.create_job_post, name='create_job_post'),
    path('update/<int:id>/',views.update_job_post,name='update_job_post'),
    path('delete/<int:id>/',views.delete_job_post,name='delete_job_post'),
    path('freepost/<int:post_id>/', views.job_free_post_detail, name='job_free_post_detail'),
    path('freepost/create/', views.create_job_free_post, name='create_job_free_post'),
    path('freepost/update/<int:id>/', views.update_job_free_post, name='update_job_free_post'),
    path('freepost/delete/<int:id>/', views.delete_job_free_post, name='delete_job_free_post'),
    path("report/create/", views.report_create_j, name="report_create_j"),
    path("company/search/", views.search_company, name="search_company"),
]

comment/models.py
from django.db import models
from employ.models import Postable

# Create your models here.
class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    postable = models.ForeignKey('employ.Postable', on_delete=models.CASCADE, blank = True)
    userable = models.ForeignKey('account.Userable', on_delete=models.CASCADE,blank = True)

class Reply(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.ForeignKey('comment.Comment', on_delete=models.CASCADE)
    userable = models.ForeignKey('account.Userable', on_delete=models.CASCADE)

util/models.py
from django.db import models

class Like(models.Model):
    userable = models.ForeignKey('account.Userable', on_delete=models.CASCADE, null=True)
    postable = models.ForeignKey("employ.Postable", on_delete=models.CASCADE, null=True)

class Dislike(models.Model):
    userable = models.ForeignKey("account.Userable", on_delete=models.CASCADE, null=True)
    postable = models.ForeignKey("employ.Postable", on_delete=models.CASCADE, null=True)

class Interest(models.Model):
    name = models.CharField(max_length=16, null=False, default='')

class UserInterest(models.Model):
    interest = models.ForeignKey("util.Interest", on_delete=models.CASCADE, null=True)
    userable = models.ForeignKey("account.Userable", on_delete=models.CASCADE, null=True, related_name = "interest")

class Hashtag(models.Model):
    name = models.CharField(max_length=10, null=False, default='')
    postable = models.ManyToManyField('employ.Postable', related_name='posts')

class Rating(models.Model):
    STARS = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    rate = models.IntegerField(choices=STARS, null=False, default='0')

class EmployerRating(models.Model):
    employer = models.ForeignKey("account.Employer", on_delete=models.CASCADE, null=True)
    applicant = models.ForeignKey("account.Applicant", on_delete=models.CASCADE, null=True)
    rating = models.ForeignKey("util.Rating", on_delete=models.CASCADE, null=True)

templates/Post/postCheck.html
{% load static %}
<!--게시글 리스트 페이지 & 게시글 확인 페이지-->
<!DOCTYPE html>
<html lang="ko">

<head>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <!--<link rel="stylesheet" href=".static/css/postCheck.css" />-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/post/postView.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/post/postCheck.css' %}" />

    </script>
    <title>게시글 확인 페이지</title>
</head>

<body>
    {% include "header2.html" %}
        <div class="backg">
            <div id="header">
                <div id="title-wrap">
                    <h3 class="nickname">{{post.userable.name}}</h3>
                    <h2 class="title">{{post.title}}</h2>
                </div>
                <div id="inform-wrap">
                    {% if post.userable == request.user %}
                    <a href="{% url 'employ:update_employ_post' post.id %}" class="modify">수정하기</a>
                    <a href="{% url 'employ:delete_employ_post' post.id %}" class="delete">삭제하기</a>
                    {% else %}

                    <p class="reportText">신고하기</p>
                    {% endif %}
                    <div class="reportMenu2" style="display: none;">
                        <select id="reportReason2">
                            <option value="">사유를 선택하세요</option>
                            <option value="사칭/사기">사칭/사기</option>
                            <option value="욕설/비하">욕설/비하</option>
                            <option value="상업적 광고 및 판매">상업적 광고 및 판매</option>
                            <option value="기타">기타</option>
                        </select>
                        <button id="report-submit2">신고</button>
                    </div>
                    <h2 class="views">조회수 {{post.views}}회</h2>
                </div>
            </div>

            <div class="rectangleBar"></div>
            <div id = "infoBox-wrap">
                <div class="infoBoxLineUp"></div>
                <div id = "infoBox-content">
                    <div class="infoBox">
                        <h2 class="infoCondition">지원조건({{post.employ_shape}})</h2>
                        <h2 class="infoCondition">평점
                            <br>
                            <div class="star-rating space-x-4 mx-auto">
                                {% if 1 <= post.rating %}
                                <span class="star" id="1-star" value="1">★</span>
                                {% else %}
                                <span class="star" id="1-star" value="1">&#9734;</span>
                                {% endif %}
                                {% if 2 <= post.rating %}
                                <span class="star" id="2-star" value="2">★</span>
                                {% else %}
                                <span class="star" id="2-star" value="2">&#9734;</span>
                                {% endif %}
                                {% if 3 <= post.rating %}
                                <span class="star" id="3-star" value="3">★</span>
                                {% else %}
                                <span class="star" id="3-star" value="3">&#9734;</span>
                                {% endif %}
                                {% if 4 <= post.rating %}
                                <span class="star" id="4-star" value="4">★</span>
                                {% else %}
                                <span class="star" id="4-star" value="4">&#9734;</span>
                                {% endif %}
                                {% if 5 <= post.rating %}
                                <span class="star" id="5-star" value="5">★</span>
                                {% else %}
                                <span class="star" id="5-star" value="5">&#9734;</span>
                                {% endif %}
                            </div>
                        </h2>
                        <h2 class="infoCondition">해시태그<br>[
                            {% for hashtag in hashtags %}
                                {% if not forloop.first %}
                                ,&nbsp;
                                {% endif %}
                                {{hashtag}}
                            
                            {% endfor %}
                            ]</h2>
                    </div>
                    <div class="infoBoxLineMiddle"></div>
                    <div class="infoBox2">
                        <h2 class="infoCondition">회사명<br>[{{post.search_company}}]</h2>
                    </div>
                </div>
                <div class="infoBoxLineDown"></div>
            </div>
            
            


            
            
            

            <h2 class="contentText">게시글 내용</h2>
            <div class="contentBox">
                <img id = "contentImg" src = "{{post.image.url}}">
                <div id = "text-wrap">{{post.content}}</div>
            </div>
            <div class="contentBoxUp"></div>
            <div class="contentBoxDown"></div>

            <div id = "button-wrap">
                <button class="goodButton" type="button" value="Button" onclick="toggleLike()">
                    <h2 class="goodText">{{post.like_set.count}}👍<br>좋아요</h2>
                </button>
        
                <button class="badButton" type="button" value="Button" onclick="toggleDislike()">
                    <h2 class="badText">{{post.dislike_set.count}}👎<br>싫어요</h2>
                </button>
            </div> 


            <h2 class="commentText">댓글</h2>

            <div class="commentBoxUp"></div>
        <div class="commentBox">

            <div id="comment-list">
                {% for comment in post.comment_set.all %}
                <div id="{{comment.id}}" class="comment">
                    <p>[{{comment.userable.name}}]</p>
                    <p class="comment_content">{{comment.content}}</p>
                    <div class="comment-options">
                        <button class="recomment" onclick="createReplyForm(this)">대댓글 달기</button>
                        <!--<button onclick = "location.href = '{% url 'job:update_job_post' post.id %}'">수정하기</button>-->
                        <button class="comment_update" onclick="updateComment(this)">수정하기</button>
                        <delete-button>삭제하기</delete-button>
                    </div>
                    {% for reply in comment.reply_set.all %}
                    <div id="{{reply.id}}" class="reply">
                        <p>└ RE: [{{reply.userable.name}}]</p>
                        <p class="reply_content">{{reply.content}}</p>
                        <div class="comment-options">
                            <button class="reply_update" onclick="updateReply(this)">수정하기</button>
                            <delete-button onclick="deleteReply(this)"> 삭제하기</delete-button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <div class="comment-input-container">
                <textarea id="comment-input" placeholder="댓글을 작성하세요"></textarea>
                <button id="comment-submit">SEND</button>
            </div>
        </div>
        

        
        <div class="commentBoxDown"></div>
        </div>

        <script type="text/javascript">var post_id = "{{post.id}}"</script>
        <script src="{% static 'js/post/postCheck.js' %}"></script>
</body>

</html>

<!--좋아요/싫어요 버튼 클릭 기능 구현 -->

templates/Post/postFree.html
{% load static %}
<!--게시글 리스트 페이지 & 게시글 확인 페이지-->
<!DOCTYPE html>
<html lang="ko">

<head>
    <!--<link rel="stylesheet" href=".static/css/postCheck.css" />-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/post/postView.css' %}" />
    </script>
    <title>게시글 확인 페이지</title>
</head>

<body>
    {% include 'header2.html' %}
    <div class="backg">
        <div id="header">
            <div id="title-wrap">
                <h3 class="nickname">{{post.userable.name}}</h3>
                <h2 class="title">{{post.title}}</h2>
            </div>
            <div id="inform-wrap">
                {% if post.userable == request.user %}
                <a href="{% url 'employ:update_employ_post' post.id %}" class="modify">수정하기</a>
                <a href="{% url 'employ:delete_employ_post' post.id %}" class="delete">삭제하기</a>
                {% else %}

                <p class="reportText">신고하기</p>
                {% endif %}
                <div class="reportMenu2" style="display: none;">
                    <select id="reportReason2">
                        <option value="">사유를 선택하세요</option>
                        <option value="사칭/사기">사칭/사기</option>
                        <option value="욕설/비하">욕설/비하</option>
                        <option value="상업적 광고 및 판매">상업적 광고 및 판매</option>
                        <option value="기타">기타</option>
                    </select>
                    <button id="report-submit2">신고</button>
                </div>
                <h2 class="views">조회수 {{post.views}}회</h2>
            </div>
        </div>
        <div class="rectangleBar"></div>

        <h2 class="contentText">게시물내용</h2>
        <div class="contentBoxUp"></div>
        <div class="contentBox">
            <img id="contentImg" src="{{post.image.url}}">
            <div id="text-wrap">{{post.content}}</div>
        </div>

        <div class="contentBoxDown"></div>

        <div id="button-wrap">
            <button class="goodButton" type="button" value="Button" onclick="toggleLike()">
                <h2 class="goodText">{{post.like_set.count}}👍<br>좋아요</h2>
            </button>

            <button class="badButton" type="button" value="Button" onclick="toggleDislike()">
                <h2 class="badText">{{post.dislike_set.count}}👎<br>싫어요</h2>
            </button>
        </div>


        <h2 class="commentText">댓글</h2>
        <div class="commentBoxUp"></div>
        <div class="commentBox">

            <div id="comment-list">
                {% for comment in post.comment_set.all %}
                <div id="{{comment.id}}" class="comment">
                    <p>[{{comment.userable.name}}]</p>
                    <p class="comment_content">{{comment.content}}</p>
                    <div class="comment-options">
                        <button class="recomment" onclick="createReplyForm(this)">대댓글 달기</button>
                        <!--<button onclick = "location.href = '{% url 'job:update_job_post' post.id %}'">수정하기</button>-->
                        <button class="comment_update" onclick="updateComment(this)">수정하기</button>
                        <delete-button>삭제하기</delete-button>
                    </div>
                    {% for reply in comment.reply_set.all %}
                    <div id="{{reply.id}}" class="reply">
                        <p>└ RE: [{{reply.userable.name}}]</p>
                        <p class="reply_content">{{reply.content}}</p>
                        <div class="comment-options">
                            <button class="reply_update" onclick="updateReply(this)">수정하기</button>
                            <delete-button onclick="deleteReply(this)"> 삭제하기</delete-button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <div class="comment-input-container">
                <textarea id="comment-input" placeholder="댓글을 작성하세요"></textarea>
                <button id="comment-submit">SEND</button>
            </div>
        </div>



        <div class="commentBoxDown"></div>

    </div>



    <script src="{% static 'js\post\postView.js' %}"></script>
    <script type="text/javascript">var post_id = "{{post.id}}"</script>
</body>

</html>

<!--좋아요/싫어요 버튼 클릭 기능 구현 -->

templates/Post/postList.html
{% load static %}
<!--게시글 리스트 페이지 & 게시글 확인 페이지-->
<!DOCTYPE html>
<html lang="ko">

<head>
    
    <link rel="stylesheet" rel="stylesheet" href="{% static 'css\post\postList.css' %}" />
    <link rel="stylesheet" rel="stylesheet" href="{% static 'css\pagination.css' %}" />

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</script>

    <title>구직 커뮤니티</title>

</head>

<body>
    {% include 'header2.html' %}
    <!--구직 커뮤니티-->
    <!--선택 박스-->
    <div class="searchBoxes">
        <button class="searchBox" type="button" value="Button">관심분야</button>
        <button class="searchBox" type="button" value="Button">경력</button>
        <button class="searchBox" type="button" value="Button">신입</button>
      </div>
    <!--검색기능 + 옵션 => 분류: 제목, 내용, 제목+내용, 해시태그, 회사명-->
    <div class="searchContainer">
		<div class="row">
            <form action="index/search" method="GET"></form>
				<table class="pull-right">
					<tr>
						<td><select class="form-control" name="searchField">
								<option value="0">분류</option>
								<option value="title">제목</option>
								<option value="content">내용</option>
								<option value="titleContent">제목+내용</option>
								<option value="hashTag">해시태그</option>
								<option value="company">회사명</option>
						</select></td>
						<td><input type="text" class="form-control"
							placeholder="검색어 입력" name="searchText" maxlength="100"></td>
						<td><button type="submit" class="btn btn-success">검색</button></td>
					</tr>
				</table>
			</form>
		</div>
	</div>

    <h2 id="searchResultHeading" style="display: none;"></h2>
    <div id="searchResults"></div>
    
    
    <!--게시글(박스) 누르면 다음 페이지로 이동 => 링크는 js에서 임의로 설정-->
    <div id="postList"></div>
       <!--위 박스 게시글 (조회수순)-->
    

    <h2 class="posting">실시간 게시글<hr /></h2>

    <div id="linePostListContainer">
        <!--게시글(줄) 누르면 다음 페이지로 이동 => 링크는 js에서 임의로 설정-->
        <div id="linePostList"></div>   <!--아래 줄 게시글-->
    </div>
    <div id="newPostContainer"></div>   <!--아래 실시간 게시물-->


    <div class="container">
        <div class="button-container" id="buttonContainer"></div>
    </div>
    
    <script src="{% static 'js\post\postList.js' %}"></script>
    <script src="{% static 'js\pagination.js' %}"></script>

</body>
</html>

templates/Post/postView.html
{% load static %}
<!--게시글 리스트 페이지 & 게시글 확인 페이지-->
<!DOCTYPE html>
<html lang="ko">

<head>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link type="text/css" rel="stylesheet" href="{% static 'css/post/postView.css' %}" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </script>

    <title>게시글 확인 페이지</title>

</head>

<body>
    {% include "header2.html" %}
    <div class="backg">
        <div id = "header">
            <div id = "title-wrap">
                <h3 class="nickname">{{post.userable.name}}</h3>
                <h2 class="title">{{post.title}}</h2>
            </div>
            <div id = "inform-wrap">
                {% if post.userable == request.user %}
                <a href="{% url 'employ:update_employ_post' post.id %}" class="modify">수정하기</a>
                <a href="{% url 'employ:delete_employ_post' post.id %}" class="delete">삭제하기</a>
                {% else %}

                <p class="reportText">신고하기</p>
                {% endif %}
                <div class="reportMenu2" style="display: none;">
                    <select id="reportReason2">
                        <option value="">사유를 선택하세요</option>
                        <option value="사칭/사기">사칭/사기</option>
                        <option value="욕설/비하">욕설/비하</option>
                        <option value="상업적 광고 및 판매">상업적 광고 및 판매</option>
                        <option value="기타">기타</option>
                    </select>
                    <button id="report-submit2">신고</button>
                </div>
                <h2 class="views">조회수 {{post.views}}회</h2>
            </div>
        </div>
        
        
        <div class="rectangleBar">
            <h2 class="rectText1"><a  href="{% url 'employ:employ_post_detail' post.id %}">모집공고</a></h2>
            <div class="rectMiddle"></div>
            <h2 class="rectText2"><a href="{% url 'employ:QA_list' post.id %}">Q&A</a></h2>
        </div>

        <div id = "infoBox-wrap">
            <div class="infoBoxLineUp"></div>
        
            <div id = "infoBox-content">
                <div class="infoBox">
                    <h2 class="infoCondition">고용형태(인턴/정규직/비정규직)<br>[{{post.employ_shape}}]</h2>
                    <h2 class="infoEmployCount">채용자 수<br>[{{post.required_num}}]</h2>
                    <h2 class="infoEmployPrefer">우대조건<br>[{{post.prefer_condition}}]</h2>
                </div>
                <div class="infoBoxLineMiddle"></div>
                <div class="infoBox2">
                    <h2 class="infoApplyMethod">지원 방법<br>[{{post.apply_method}}]</h2>
                    <h2 class="infoApplySchedule">지원 일정<br>[{{post.start_date|date:'Y-m-d'}} ~ {{post.end_date|date:'Y-m-d'}}]</h2>
        
                </div>
            </div>
            
            <div class="infoBoxLineDown"></div>
        </div>
        


        

        <h2 class="contentText">공고 내용</h2>
        <div class="contentBoxUp"></div>
        <div class="contentBox">
            <img id = "contentImg" src = "{{post.image.url}}">
            <div id = "text-wrap">{{post.content}}</div>
        </div>
        <div class="contentBoxDown"></div>


        <h2 class="companyText">기업 정보</h2>
        <div class="companyBoxUp"></div>
        <div class="companyBox">
            <!--companyImageText-->
            <button class="companyImage" type="button" value="Button">
                <h2>image</h2>
            </button>
            <div id = "company-text-wrap">
                <h2 class="companyWriter">작성자 : {{post.userable.name}}</h2>
                <h2 class="companyDate">업로드 일자 : {{post.created_at|date:'Y-m-d'}}</h2>
                <h2 class="companyName">회사명 : {{post.userable.company}}</h2>
                <h2 class="companyType">회사업종 : 
                    {% for interest in post.userable.interest.all %}
                        {% if not forloop.first %}
                            ,&nbsp;
                        {% endif %}
                        {{interest.interest.name}}
                        
                    {% endfor %}
                </h2>
            </div>
            
        </div>
        <div class="companyBoxDown"></div>


        <div id = "button-wrap">
            <button class="goodButton" type="button" value="Button" onclick="toggleLike()">
                <h2 class="goodText">{{post.like_set.count}}👍<br>좋아요</h2>
            </button>
    
            <button class="badButton" type="button" value="Button" onclick="toggleDislike()">
                <h2 class="badText">{{post.dislike_set.count}}👎<br>싫어요</h2>
            </button>
        </div>  
        


        <div class="reportMenu" style="display: none;">
            <select id="reportReason">
                <option value="">사유를 선택하세요</option>
                <option value="사칭/사기">사칭/사기</option>
                <option value="욕설/비하">욕설/비하</option>
                <option value="상업적 광고 및 판매">상업적 광고 및 판매</option>
                <option value="기타">기타</option>
            </select>
            <button id="report-submit">신고</button>
        </div>


        <h2 class="commentText">댓글</h2>
        <div class="commentBoxUp"></div>
        <div class="commentBox">

            <div id="comment-list">
                {% for comment in post.comment_set.all %}
                <div id="{{comment.id}}" class="comment">
                    <p>[{{comment.userable.name}}]</p>
                    <p class="comment_content">{{comment.content}}</p>
                    <div class="comment-options">
                        <button class="recomment" onclick="createReplyForm(this)">대댓글 달기</button>
                        <!--<button onclick = "location.href = '{% url 'job:update_job_post' post.id %}'">수정하기</button>-->
                        <button class="comment_update" onclick="updateComment(this)">수정하기</button>
                        <delete-button>삭제하기</delete-button>
                    </div>
                    {% for reply in comment.reply_set.all %}
                    <div id="{{reply.id}}" class="reply">
                        <p>└ RE: [{{reply.userable.name}}]</p>
                        <p class="reply_content">{{reply.content}}</p>
                        <div class="comment-options">
                            <button class="reply_update" onclick="updateReply(this)">수정하기</button>
                            <delete-button onclick="deleteReply(this)"> 삭제하기</delete-button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <div class="comment-input-container">
                <textarea id="comment-input" placeholder="댓글을 작성하세요"></textarea>
                <button id="comment-submit">SEND</button>
            </div>
        </div>
        

        
        <div class="commentBoxDown"></div>
    </div>



    <script type="text/javascript">var post_id = "{{post.id}}"</script>
    <script src="{% static 'js/post/postView.js' %}"></script>
</body>

</html>