config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Audience import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employ/', include('employ.urls')),
    path('job/', include('job.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include('account.urls')),
    path('util/', include('util.urls')),
    path('audience/', include('Audience.urls')),
    path('', views.intro_view, name='intro_view'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employ/urls.py
from django.urls import path
from . import views as views

app_name = "employ"
urlpatterns = [
    path('<int:post_id>/', views.employ_post_detail, name='employ_post_detail'),
    path('create/', views.create_employ_post, name='create_employ_post'),
    path('update/<int:id>/', views.update_employ_post, name='update_employ_post'),
    path('delete/<int:id>/', views.delete_employ_post, name='delete_employ_post'),
    path('freepost/<int:post_id>/', views.employ_free_post_detail, name='employ_free_post_detail'),
    path('freepost/create/', views.create_employ_free_post, name='create_employ_free_post'),
    path('freepost/update/<int:id>/', views.update_employ_free_post, name='update_employ_free_post'),
    path('freepost/delete/<int:id>/', views.delete_employ_free_post, name='delete_employ_free_post'),
    path("question/list/", views.QA_list_data, name="QA_list_data"),
    path("question/list/<int:id>", views.QA_list, name="QA_list"),
    path('question/create/<int:post_id>/', views.create_question, name='create_question'),
    path('question/update/<int:post_id>/', views.update_question, name='update_question'),
    path('question/<int:post_id>/<int:question_id>/', views.question_detail, name='question_detail'),
    path('question/delete/<int:post_id>/', views.delete_question, name='delete_question'),
    path('answer/create/<int:post_id>/<int:question_id>/', views.create_answer, name='create_answer'),
    path('answer/update/<int:post_id>/<int:question_id>/', views.update_answer, name='update_answer'),
    path('answer/delete/<int:post_id>/<int:question_id>/', views.delete_answer, name='delete_answer'),
    path("report/create/", views.report_create_e, name="report_create_e"),
    path('post/<int:post_id>/', views.post_detail, name='post_detail')
]

job/urls.py
from django.urls import path
from . import views as views

app_name = "job"
urlpatterns = [
    path('<int:post_id>/', views.job_post_detail, name='job_post_detail'),
    path('create/', views.create_job_post, name='create_job_post'),
    path('update/<int:id>/',views.update_job_post,name='update_job_post'),
    path('delete/<int:id>/',views.delete_job_post,name='delete_job_post'),
    path('freepost/<int:post_id>/', views.job_free_post_detail, name='job_free_post_detail'),
    path('freepost/create/', views.create_job_free_post, name='create_job_free_post'),
    path('freepost/update/<int:id>/', views.update_job_free_post, name='update_job_free_post'),
    path('freepost/delete/<int:id>/', views.delete_job_free_post, name='delete_job_free_post'),
    path("report/create/", views.report_create_j, name="report_create_j"),
    path("company/search/", views.search_company, name="search_company"),
]

util/models.py
from django.db import models

class Like(models.Model):
    userable = models.ForeignKey('account.Userable', on_delete=models.CASCADE, null=True)
    postable = models.ForeignKey("employ.Postable", on_delete=models.CASCADE, null=True)

class Dislike(models.Model):
    userable = models.ForeignKey("account.Userable", on_delete=models.CASCADE, null=True)
    postable = models.ForeignKey("employ.Postable", on_delete=models.CASCADE, null=True)

class Interest(models.Model):
    name = models.CharField(max_length=16, null=False, default='')

class UserInterest(models.Model):
    interest = models.ForeignKey("util.Interest", on_delete=models.CASCADE, null=True)
    userable = models.ForeignKey("account.Userable", on_delete=models.CASCADE, null=True, related_name = "interest")

class Hashtag(models.Model):
    name = models.CharField(max_length=10, null=False, default='')
    postable = models.ManyToManyField('employ.Postable', related_name='posts')

class Rating(models.Model):
    STARS = [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    rate = models.IntegerField(choices=STARS, null=False, default='0')

class EmployerRating(models.Model):
    employer = models.ForeignKey("account.Employer", on_delete=models.CASCADE, null=True)
    applicant = models.ForeignKey("account.Applicant", on_delete=models.CASCADE, null=True)
    rating = models.ForeignKey("util.Rating", on_delete=models.CASCADE, null=True)

templates/findwork_company_QnA/QnA_answer_w.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css\findwork_company_QnA\QnA_answer_w_style.css' %}">

</head>
<body>
    {% include 'header2.html' %}
    <form action="{% url 'employ:create_answer' post.id question.id %}" method="POST" enctype="multipart/form-data">

    {% comment %} <form action="{% url 'employ:create_question' post.id %}" method="POST"> {% endcomment %}

        <div class="container">
            <input type="text" style="border:0 solid black" id="title4" name="title" value="제목:Re [{{question.title}}]" readonly>
            

    
            <textarea id="content" style="border:0 solid black" name="content" placeholder="내용을 입력해주세요"></textarea>
        
            <input type="submit" id="upload_btn" value="업로드하기">
        </div>
    </form>
    <script src="{% static 'js\findwork_company_QnA\QnA_answer_w_script.js' %}"></script>
</body>

templates/findwork_company_QnA/QnA_question_w.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/findwork_company_QnA/QnA_question_w_style.css' %}">

</head>
<body>
    {% include 'header2.html' %}

    <form action="{% url 'employ:create_question' post.id  %}" method="POST" enctype="multipart/form-data">

        <div class="container">
            <input type="text" style="border:0 solid black" id="title3" value = "{{question.title}}" name="title" placeholder="제목을 입력해주세요">
            
            <div class="certification_photo">
                <b id= "certification_photo_text">사진첨부</b>
    
                <div id="certification_photo_space">
                    <div id="preview-container"></div>
                </div>
    
                <input type="file" id="upload-input" name = "image" accept="image/*">
                <label for="upload-input" class="upload-button">사진 불러오기</label>
                
            </div>
    
            <textarea id="content" style="border:0 solid black" name="content" placeholder="내용을 입력해주세요"></textarea>
        
            <input type="submit" id="upload_btn" value="업로드하기">
        </div>
    </form>
    <script src="{% static 'js/findwork_company_QnA/QnA_question_w_script.js' %}"></script>
</body>

templates/findwork_company_QnA/companyname.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/findwork_company_QnA/companyname.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
</head>
<body>
    <div class="search_wrapper">
      <div class="mid_wrapper">
        <!-- 검색창 -->
        <input type="text" id="name" autocomplete="off" placeholder="회사명을 검색하세요">
        <!-- 검색버튼 -->
        <input type="button" id="submit_button" value="🔍"> 
      </div>
      <!-- 추천창 -->
      <div id="suggestion_box" class="invisible">
        <div id="suggested_items"></div>
      </div>
    </div>
    <input type="text" style="border:0 solid black" id="company_name" name="name" placeholder="회사 검색하기" onclick="openNewWindow()">
  <script src="{% static 'js/findwork_company_QnA/companyname.js' %}"></script>
</body>
</html>

templates/findwork_company_QnA/free_write.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/findwork_company_QnA/free_write_style.css' %}">

</head>
<body>
{% include 'header2.html' %}
    {% if type == "post_j" %}
        {% if post %}
            <form action="{% url 'job:update_job_free_post' post.id %}" method="POST" enctype="multipart/form-data">
        {% else %}
            <form action="{% url 'job:create_job_free_post' %}" method="POST" enctype="multipart/form-data">
        {% endif %}
    {% else %}
        {% if post %}
            <form action="{% url 'employ:update_employ_free_post' post.id %}" method="POST" enctype="multipart/form-data">
        {% else %}
            <form action="{% url 'employ:create_employ_free_post' %}" method="POST" enctype="multipart/form-data">
        {% endif %}
    {% endif %}
        <div class="container">
            <b id= "certification_photo_text">제목</b>
            <input type="text" style="border:0 solid black" id="title5" name="title" value = "{{post.title}}" placeholder="제목을 입력해주세요">
            
            <div class="certification_photo">
                <b id= "certification_photo_text">사진첨부</b>
    
                <div id="certification_photo_space">
                    <div id="preview-container"></div>
                </div>
    
                <input type="file" id="upload-input" name = "image" value = "{{post.image.url}}" accept="image/*">
                <label for="upload-input" class="upload-button">사진 불러오기</label>
         
            </div>
            <b id= "certification_photo_text">내용</b>
            <textarea id="content" style="border:0 solid black" name="content" placeholder="내용을 입력해주세요">{{post.content}}</textarea>
    
            <b id="hashtag_text">해시태그</b>
            <div id="input-container" class="input-container">
                <input type="text" id="tag-input" name = "hashtag" value="#" maxlength="30">
            </div>
            
            <div id="tag-container" class="tag-container">
                {% for hashtag in post.hashtag_set.all %}
                    <input type="text" class="tag-input" value="#{{hashtag.name}}" style="width: 43.6px;">
                {% endfor %}
            </div>
        
            <input type="submit" id="upload_btn" value="업로드하기">
        </div>
    </form>
    <script src="{% static 'js/findwork_company_QnA/free_write_script.js' %}"></script>
</body>

templates/findwork_company_QnA/write_company.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/findwork_company_QnA/write_company_style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

</head>
<body>
    {% include 'header2.html' %}
    {% if post %}
        <form action="{% url 'employ:update_employ_post' post.id %}" method="POST" enctype="multipart/form-data">
    {% else %}
        <form action="{% url 'employ:create_employ_post' %}" method="POST" enctype="multipart/form-data">

    {% endif %}
        <div class="container">
            <b class="title">제목</b>
            <input type="text" style="border:0 solid black" id="title2" name="title" value = "{{post.title}}"placeholder="제목을 입력해주세요">
            <div class="certification_photo">
                <b id="certification_photo_text">인증사진</b>

                <div id="certification_photo_space">
                    <div id="preview-container"></div>
                </div>
                <input type="file" id="upload-input" name = "image" src = "{{post.image.url}}"accept="image/*">
                <label for="upload-input" class="upload-button">사진 불러오기</label>
                
            </div>
            <b class="title">내용</b>
            <textarea id="content" style="border:0 solid black" name="content" placeholder="내용을 입력해주세요">{{post.content}}</textarea>
            <b id="job_condition_text">고용형태(인턴/정규직/비정규직)</b>
            <div class="job_btn">
                <input type="text" id="employ_shape" name = "employ_shape" value="{{post.employ_shape}}">
                <label class="job_shape" id="intern_btn">인턴</label>
                <label class="job_shape" id="permanent_btn">정규직</label>
                <label class="job_shape" id="temporary_btn">비정규직</label>
            </div>

            <b id="career_text">경력</b>
            <div class="career_btn">
                <input type="text" id="career" name = "career" value = "{{post.career}}">
                <label class="career" id="newcomer_btn">신입</label>
                <label class="career" id="experienced_btn">경력</label>
            </div>

            <b id="num_recruiters_text">채용자수</b>
            <input type="text" id="numeric-input" name = "required_num" oninput="handleInput(event)" value = "{{post.required_num}}" placeholder="숫자입력">

            <b id="preferential_terms_text">우대조건</b>
            <textarea id="preferential_terms" style="border:0 solid black" name="prefer_condition" placeholder="내용을 입력해주세요">{{post.prefer_condition}}</textarea>

            <b id="how_to_apply_text">지원방법</b>
            <textarea id="how_to_apply" style="border:0 solid black" name="apply_method" placeholder="내용을 입력해주세요">{{post.apply_method}}</textarea>

            <b id="support_schedule_text">지원일정</b>
            <div class="support_schedule">
                <div class="calendar-1">
                    <label for="start-date"></label>
                    <input type="text" id="start-date" name = "start_date" value = "{{post.start_date}}" placeholder="지원시작 일자" readonly>
                </div>
                <b id="swung_dash">~</b>
                <div class="calendar-2">
                    <label for="end-date"></label>
                    <input type="text" id="end-date" name = "end_date" value = "{{post.end_date}}" placeholder="지원마감 일자" readonly>
                </div>
            </div>
            <b id="hashtag_text">해시태그</b>
            <div id="input-container" class="input-container">
                <input type="text" id="tag-input" maxlength="30">

            </div>
            <div id="tag-container" class="tag-container">
                {% for hashtag in hashtags %}
                    <input type="text" name = "hashtag" class="tag-input" value="{{hashtag}}" style="width: 43.6px;">
                {% endfor %}
            </div>

            <input type="submit" id="upload_btn" value="업로드하기">
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="{% static 'js/findwork_company_QnA/write_company_script.js' %}"></script>
</body>

templates/findwork_company_QnA/write_findwork.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css\findwork_company_QnA\write_findwork_style.css' %}">

</head>
<body>
{% include "header2.html" %}
    {% if post %}
        <form action="{% url 'job:update_job_post' post.id %}" method="POST" enctype="multipart/form-data">
    {% else %}
        <form action="{% url 'job:create_job_post' %}" method="POST" enctype="multipart/form-data">

    {% endif %}
            <div class="container">
                <b id="job_condition_text">제목</b>
                <input type="text" style="border:0 solid black" id="title1" name="title" value = "{{post.title}}" placeholder="제목을 입력해주세요">
                <b id="job_condition_text">내용</b>
                <textarea id="content" style="border:0 solid black" name="content" placeholder="내용을 입력해주세요">{{post.content}}</textarea>
                <b id="job_condition_text">지원조건</b>
                <div class="job_btn">
                    <input type="text" id="employ_shape" name = "employ_shape" value="{{post.employ_shape}}">
                    <label class="job_shape" id="intern_btn">인턴</label>
                    <label class="job_shape" id="permanent_btn">정규직</label>
                    <label class="job_shape" id="temporary_btn">비정규직</label>
                </div>

                <b id="company_name_text">회사 이름</b>
                <input id = "search-company" name = "search_company" type = "text" name = "name" placeholder="회사 검색하기">


                <b id="grade_text">평점</b>
                <input type="number" name="rating" id="star_number" value = "{{post.rating}}"style="display: none;">
                <div class="rating">
                    <span class="star" id="star_1" data-value="1" onclick="setRating(1)">★</span>
                    <span class="star" id="star_2" data-value="2" onclick="setRating(2)">★</span>
                    <span class="star" id="star_3" data-value="3" onclick="setRating(3)">★</span>
                    <span class="star" id="star_4" data-value="4" onclick="setRating(4)">★</span>
                    <span class="star" id="star_5" data-value="5" onclick="setRating(5)">★</span>
                </div>
                <b id="certification_photo_text">인증사진</b>
                <div class="certification_photo">
                    

                    <div id="certification_photo_space">
                        <div id="preview-container"></div>
                    </div>

                    <input type="file" id="upload-input" name = "image" src = "{{post.image.url}}"accept="image/*">
                    <label for="upload-input" class="upload-button">사진 불러오기</label>
                
                </div>
                <b id="hashtag_text">해시태그</b>
                <div id="input-container" class="input-container">
                    <input type="text" id="tag-input" name = "hashtag"  maxlength="30">


                </div>

                <div id="tag-container" class="tag-container">
                    {% for hashtag in post.hashtag_set.all %}
                        <input type="text" class="tag-input" value="#{{hashtag.name}}" style="width: 43.6px;">
                    {% endfor %}
                </div>

                <input type="submit" id="upload_btn" value="업로드하기">
                
            </div>

        </form>
        <div class="search_wrapper">
            <div class="mid_wrapper">
              <!-- 검색창 -->
              <input type="text" id="name" autocomplete="off" placeholder="회사명을 검색하세요">
              <!-- 검색버튼 -->
              <input type="button" id="submit_button" value="🔍"> 
            </div>
            <!-- 추천창 -->
            <div id="suggestion_box" class="invisible">
            </div>
          </div>
    <script src="{% static 'js\findwork_company_QnA\write_findwork_script.js' %}"></script>
    <script src="{% static 'js/findwork_company_QnA/companyname.js' %}"></script>

</body>